### ISSUE TITLE
After pressing Right to expand a directory, pressing Down takes you back to the top of the list

### ISSUE THREAD

**Issue by Dwedit** [trigger-death/WinDirStat.Net#1]
First of all, nice program!  But here's an issue with the user interface.

If you press Right on the keyboard to expand a directory, then press Down, the cursor is moved to the top of the list, rather than the first item of the directory you just expanded.

**Comment by trigger-segfault** [comment]
There's actually quite a few issues right now that need to be addressed. Deleting files and performing certain operations during scan is still pretty flaky. That's what I get for my first go at implementing MVVM *and* extreme memory + speed optimization. Thank you for the PR, lemme check it out.

**Comment by trigger-segfault** [comment]
I've merged the PR, issue should be resolved now.
